name: docs
channels:

  - conda-forge
  - pytorch

  - defaults

dependencies:

  # Base depends
  - python
  - pip

  # Package dependencies
  - numpy
  - pandas
  - pytorch
  - matplotlib

  # Pip-only installs
  - pip:
    - sphinx-copybutton
    - furo
    - nbsphinx

